### ISSUE TITLE
Build Time Deprecations don't seem to be silenced

### ISSUE THREAD

**Issue by joegaudet** [mixonic/ember-cli-deprecation-workflow#153]
Configuration like so:

```
    { handler: 'silence', matchId: 'template-compiler.registerPlugin' },
```

But getting a bunch of these:

```
DEPRECATION: Using class based template compilation plugins is deprecated, please update to the functional style: TransformTestSelectorParamsToHashPairs [deprecation id: template-compiler.registerPlugin]
        at logDeprecationStackTrace (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:1984:21)
        at HANDLERS.<computed> (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:2117:9)
        at raiseOnDeprecation (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:2011:9)
        at HANDLERS.<computed> (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:2117:9)
        at invoke (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:2129:9)
        at deprecate (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:2085:28)
        at wrapLegacyPluginIfNeeded (/Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:20501:49)
        at /Users/joegaudet/foodee-dev/MasterFox/clients/swift-fox/node_modules/ember-source/dist/ember-template-compiler.js:20482:16
        at Array.map (<anonymous>)
```

Currenly stuck on ember 3.27, would like to start working on upgrading, but would first like to silence these issues.

**Comment by simonihmig** [comment]
This should be added to docs. This addon can only cover runtime deprecations, as it runs only in the browser, not in node.
