### ISSUE TITLE
Fastboot compat

### ISSUE THREAD

**Issue by Turbo87** [mixonic/ember-cli-deprecation-workflow#43]
I'm seeing the following error after installing the addon into a project that's using fastboot:

```
There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in dist/fastboot/vendor.js on line 72638.
Because it's coming from vendor.js, an addon is most likely responsible for this error. You should look at this file and line number to determine which addon is not yet FastBoot compatible.

The full stack trace is:

Cannot set property 'config' of undefined
TypeError: Cannot set property 'config' of undefined
    at /Users/tbieniek/Code/tmp/-stickyauth/dist/fastboot/vendor.js:72638:36
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Sandbox.VMSandbox.eval (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/vm-sandbox.js:14:14)
    at EmberApp.loadAppFiles (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/ember-app.js:141:13)
    at EmberApp.retrieveSandboxedApp (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/ember-app.js:182:10)
    at new EmberApp (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/ember-app.js:48:21)
    at FastBoot._buildEmberApp (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/index.js:111:17)
    at new FastBoot (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot/dist/cjs/index.js:52:10)
    at fastbootExpressMiddleware (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/fastboot-express-middleware/index.js:24:16)
    at exec.then (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/ember-cli-fastboot/lib/tasks/fastboot-server.js:33:71)
    at tryCatch (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/tbieniek/Code/tmp/-stickyauth/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by rwjblue** [comment]
Can you share the 10 or so lines before and after dist/fastboot/vendor.js line 72638?

**Comment by Turbo87** [comment]
it looks like this was a configuration error.

`config/deprecation-workflow.js`:
```js
window.deprecationWorkflow = window.deprecationWorkflow || {}; // <- this was missing
window.deprecationWorkflow.config = {
  workflow: [
    { handler: 'silence', matchId: 'ember-metal.ember-k' },
    { handler: 'silence', matchId: 'container-lookupFactory' }
  ]
};
```
