### ISSUE TITLE
monkey-patching does not work with addons in yarn workspaces

### ISSUE THREAD

**Issue by runspired** [mixonic/ember-cli-deprecation-workflow#65]
I suspect it may have something to do with how it is reaching in to discover ember-source files

```
stack: TypeError: Cannot read property '_addon' of undefined
    at Class._monkeyPatch_EmberDeprecate (/Users/cthoburn/Github/data/node_modules/ember-cli-deprecation-workflow/index.js:63:39)
    at Class.setupPreprocessorRegistry (/Users/cthoburn/Github/data/node_modules/ember-cli-deprecation-workflow/index.js:122:12)
    at /Users/cthoburn/Github/data/node_modules/ember-cli-preprocess-registry/preprocessors.js:27:13
    at Array.forEach (<anonymous>)
    at setupRegistryForEachAddon (/Users/cthoburn/Github/data/node_modules/ember-cli-preprocess-registry/preprocessors.js:25:10)
    at Object.module.exports.setupRegistry (/Users/cthoburn/Github/data/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
    at Class.init (/Users/cthoburn/Github/data/node_modules/ember-cli/lib/models/addon.js:328:7)
    at Class.superWrapper [as init] (/Users/cthoburn/Github/data/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.init (/Users/cthoburn/Github/data/packages/-build-infra/src/addon-build-config-for-data-package.js:21:44)
    at Class.superWrapper [as init] (/Users/cthoburn/Github/data/node_modules/core-object/lib/assign-properties.js:34:20)
```

**Comment by mixonic** [comment]
Perhaps [`_findHtmlbarsPreprocessor`](https://github.com/mixonic/ember-cli-deprecation-workflow/blob/master/index.js#L54) is returning `undefined`? 

The `_addon` property here is supposed to come from https://github.com/ember-cli/ember-cli-htmlbars/blob/d31e851ee02d35c035cd81cc6ef5f1571fd81fc2/ember-addon-main.js#L43
